name: scabies_diagnosis
description: AI-Driven Scabies Diagnosis Using Smartphone-Based Skin Lesion Scanning

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  tflite_flutter: ^0.10.4
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/